// Banco de preguntas de trivia mundialista (datos públicos / hechos).
// type 'flag' muestra una bandera (code = ISO2) y opciones de países.
// type 'text' es pregunta de texto con opciones.
// answer = índice de la opción correcta.

export const TRIVIA = [
  // ── Datos del Mundial ──
  { type: 'text', q: '¿Qué país ha ganado más Copas del Mundo?', options: ['Alemania', 'Brasil', 'Italia', 'Argentina'], answer: 1 },
  { type: 'text', q: '¿Quién ganó el Mundial de Qatar 2022?', options: ['Francia', 'Argentina', 'Brasil', 'Croacia'], answer: 1 },
  { type: 'text', q: '¿Quién ganó el Mundial de Rusia 2018?', options: ['Francia', 'Croacia', 'Bélgica', 'Inglaterra'], answer: 0 },
  { type: 'text', q: '¿Quién ganó el Mundial de Brasil 2014?', options: ['Brasil', 'Argentina', 'Alemania', 'Países Bajos'], answer: 2 },
  { type: 'text', q: '¿En qué país se jugó el primer Mundial (1930)?', options: ['Uruguay', 'Brasil', 'Italia', 'Argentina'], answer: 0 },
  { type: 'text', q: '¿Quién ganó el primer Mundial de la historia?', options: ['Argentina', 'Uruguay', 'Italia', 'Brasil'], answer: 1 },
  { type: 'text', q: '¿Cuántas selecciones juegan el Mundial 2026?', options: ['32', '40', '48', '64'], answer: 2 },
  { type: 'text', q: '¿Qué tres países son sede del Mundial 2026?', options: ['USA, Canadá y México', 'México, Brasil y USA', 'Canadá, USA y Costa Rica', 'USA, México y Colombia'], answer: 0 },
  { type: 'text', q: '¿Quién es el máximo goleador en la historia de los Mundiales?', options: ['Ronaldo', 'Miroslav Klose', 'Pelé', 'Lionel Messi'], answer: 1 },
  { type: 'text', q: '¿Cuántos Mundiales ganó Italia?', options: ['2', '3', '4', '5'], answer: 2 },
  { type: 'text', q: '¿En qué Mundial debutó Ecuador por primera vez?', options: ['Corea-Japón 2002', 'Alemania 2006', 'Francia 1998', 'USA 1994'], answer: 0 },
  { type: 'text', q: '¿Qué país europeo ganó el Mundial 2010 en Sudáfrica?', options: ['Países Bajos', 'España', 'Alemania', 'Italia'], answer: 1 },
  { type: 'text', q: '¿Cada cuántos años se juega la Copa del Mundo?', options: ['2 años', '3 años', '4 años', '5 años'], answer: 2 },
  { type: 'text', q: '¿Quién fue campeón en Sudáfrica 2010?', options: ['España', 'Alemania', 'Países Bajos', 'Uruguay'], answer: 0 },
  { type: 'text', q: '¿En qué país se jugó el Mundial 2014?', options: ['Brasil', 'Sudáfrica', 'Alemania', 'Rusia'], answer: 0 },
  { type: 'text', q: '¿Qué selección ha jugado TODOS los Mundiales de la historia?', options: ['Alemania', 'Italia', 'Brasil', 'Argentina'], answer: 2 },
  { type: 'text', q: '¿Con qué selección debutó Lionel Messi en un Mundial?', options: ['Argentina', 'España', 'Uruguay', 'Chile'], answer: 0 },
  { type: 'text', q: '¿Cuántos jugadores tiene un equipo en el campo?', options: ['10', '11', '12', '9'], answer: 1 },
  { type: 'text', q: '¿Qué color de tarjeta significa expulsión?', options: ['Amarilla', 'Verde', 'Roja', 'Azul'], answer: 2 },
  { type: 'text', q: '¿Quién levantó la copa como capitán de Argentina en 2022?', options: ['Lionel Messi', 'Ángel Di María', 'Emiliano Martínez', 'Rodrigo De Paul'], answer: 0 },
  { type: 'text', q: '¿Qué país ganó el Mundial de 1998 como local?', options: ['Brasil', 'Francia', 'Italia', 'Alemania'], answer: 1 },
  { type: 'text', q: '¿Qué trofeo levanta el campeón del Mundial?', options: ['La Champions', 'La Copa Jules Rimet', 'El Trofeo de la Copa Mundial de la FIFA', 'La Eurocopa'], answer: 2 },
  { type: 'text', q: '¿Quién ganó el Mundial de Italia 1990?', options: ['Argentina', 'Alemania', 'Italia', 'Brasil'], answer: 1 },
  { type: 'text', q: '¿Quién ganó el Mundial de México 1986?', options: ['Argentina', 'Brasil', 'Alemania', 'Francia'], answer: 0 },
  { type: 'text', q: '¿Quién ganó el Mundial de España 1982?', options: ['Brasil', 'Italia', 'Alemania', 'Argentina'], answer: 1 },
  { type: 'text', q: '¿Quién ganó el Mundial de Argentina 1978?', options: ['Argentina', 'Países Bajos', 'Brasil', 'Perú'], answer: 0 },
  { type: 'text', q: '¿Quién ganó el Mundial de Estados Unidos 1994?', options: ['Italia', 'Brasil', 'Argentina', 'Bulgaria'], answer: 1 },
  { type: 'text', q: '¿Cuántos Mundiales ha ganado Brasil?', options: ['3', '4', '5', '6'], answer: 2 },
  { type: 'text', q: '¿Cuántos Mundiales ha ganado Alemania?', options: ['2', '3', '4', '5'], answer: 2 },
  { type: 'text', q: '¿Cuántos Mundiales ha ganado Argentina?', options: ['2', '3', '4', '5'], answer: 2 },
  { type: 'text', q: '¿Quién es el máximo goleador histórico de los Mundiales de Brasil?', options: ['Pelé', 'Ronaldo', 'Romário', 'Rivaldo'], answer: 1 },
  { type: 'text', q: '¿Quién ganó el Balón de Oro del Mundial 2022 (mejor jugador)?', options: ['Kylian Mbappé', 'Lionel Messi', 'Luka Modric', 'Antoine Griezmann'], answer: 1 },
  { type: 'text', q: '¿Quién fue el goleador (Bota de Oro) del Mundial 2022?', options: ['Lionel Messi', 'Olivier Giroud', 'Kylian Mbappé', 'Julián Álvarez'], answer: 2 },
  { type: 'text', q: '¿Cuántos goles anotó Kylian Mbappé en la final del Mundial 2022?', options: ['1', '2', '3', '4'], answer: 2 },
  { type: 'text', q: '¿Qué selección eliminó a Ecuador del Mundial 2006?', options: ['Inglaterra', 'Alemania', 'Brasil', 'Francia'], answer: 1 },
  { type: 'text', q: '¿Quién marcó el gol histórico de Ecuador en su debut mundialista 2002 vs. Polonia?', options: ['Iván Kaviedes', 'Agustín Delgado', 'Álex Aguinaga', 'Iván Hurtado'], answer: 1 },
  { type: 'text', q: '¿Cuántas Copas América ha ganado Ecuador?', options: ['0', '1', '2', '3'], answer: 0 },
  { type: 'text', q: '¿En qué ciudad ecuatoriana se ubica el estadio "El Capwell"?', options: ['Quito', 'Cuenca', 'Guayaquil', 'Ambato'], answer: 2 },
  { type: 'text', q: '¿Cuál es el estadio de la Selección Ecuatoriana en altura?', options: ['Atahualpa', 'Monumental', 'Rodrigo Paz Delgado', 'George Capwell'], answer: 2 },
  { type: 'text', q: '¿Cuántos años dura el mandato de un presidente de la FIFA por elección (período de gestión)?', options: ['2 años', '4 años', '6 años', '8 años'], answer: 1 },
  { type: 'text', q: '¿Cuántos minutos dura un partido de fútbol (sin alargues)?', options: ['80', '90', '100', '120'], answer: 1 },
  { type: 'text', q: '¿Cuántos árbitros principales dirigen un partido (sin VAR)?', options: ['1', '2', '3', '4'], answer: 0 },
  { type: 'text', q: '¿Qué significa la sigla VAR?', options: ['Video Asistente del Árbitro', 'Valoración Automática de Resultado', 'Variación de Árbitro', 'Verificación Audiovisual Reglamentaria'], answer: 0 },
  { type: 'text', q: '¿Cuántas tarjetas amarillas provocan una expulsión en un mismo partido?', options: ['1', '2', '3', '4'], answer: 1 },
  { type: 'text', q: '¿Qué club ha ganado más Champions League?', options: ['Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Múnich'], answer: 2 },
  { type: 'text', q: '¿En qué continente se jugó el Mundial 2002 (Corea-Japón)?', options: ['Asia', 'Europa', 'Oceanía', 'África'], answer: 0 },
  { type: 'text', q: '¿Qué selección africana llegó a semifinales del Mundial 2022, una hazaña histórica?', options: ['Senegal', 'Marruecos', 'Túnez', 'Camerún'], answer: 1 },
  { type: 'text', q: '¿Cuál fue el primer Mundial transmitido en color por televisión?', options: ['México 1970', 'Alemania 1974', 'Argentina 1978', 'España 1982'], answer: 0 },
  { type: 'text', q: '¿Qué jugador tiene el récord de más Mundiales jugados (5)?', options: ['Lionel Messi', 'Cristiano Ronaldo', 'Antonio Carbajal / Rafael Márquez / Messi', 'Diego Maradona'], answer: 2 },
  { type: 'text', q: '¿Cómo se llama el famoso gol de Maradona en 1986 ante Inglaterra?', options: ['El Gol del Siglo', 'La Mano de Dios', 'El Golazo Maracaná', 'El Gol Fantasma'], answer: 0 },
  { type: 'text', q: '¿Qué apodo recibió el gol de mano de Maradona en el mismo partido?', options: ['El Gol del Siglo', 'La Mano de Dios', 'El Robo del Siglo', 'El Engaño Mundial'], answer: 1 },

  // ── Banderas ──
  { type: 'flag', code: 'br', q: '¿De qué país es esta bandera?', options: ['Brasil', 'Argentina', 'Colombia', 'Portugal'], answer: 0 },
  { type: 'flag', code: 'ar', q: '¿De qué país es esta bandera?', options: ['Uruguay', 'Argentina', 'Guatemala', 'El Salvador'], answer: 1 },
  { type: 'flag', code: 'ec', q: '¿De qué país es esta bandera?', options: ['Colombia', 'Venezuela', 'Ecuador', 'Bolivia'], answer: 2 },
  { type: 'flag', code: 'fr', q: '¿De qué país es esta bandera?', options: ['Países Bajos', 'Francia', 'Rusia', 'Luxemburgo'], answer: 1 },
  { type: 'flag', code: 'de', q: '¿De qué país es esta bandera?', options: ['Bélgica', 'España', 'Alemania', 'Ghana'], answer: 2 },
  { type: 'flag', code: 'es', q: '¿De qué país es esta bandera?', options: ['España', 'Portugal', 'Italia', 'Colombia'], answer: 0 },
  { type: 'flag', code: 'it', q: '¿De qué país es esta bandera?', options: ['Irlanda', 'México', 'Italia', 'Hungría'], answer: 2 },
  { type: 'flag', code: 'pt', q: '¿De qué país es esta bandera?', options: ['Portugal', 'España', 'Marruecos', 'Senegal'], answer: 0 },
  { type: 'flag', code: 'uy', q: '¿De qué país es esta bandera?', options: ['Argentina', 'Uruguay', 'Grecia', 'Israel'], answer: 1 },
  { type: 'flag', code: 'co', q: '¿De qué país es esta bandera?', options: ['Venezuela', 'Ecuador', 'Colombia', 'Rumania'], answer: 2 },
  { type: 'flag', code: 'mx', q: '¿De qué país es esta bandera?', options: ['México', 'Italia', 'Irán', 'Hungría'], answer: 0 },
  { type: 'flag', code: 'gb', q: '¿De qué país es esta bandera?', options: ['Reino Unido', 'Australia', 'USA', 'Nueva Zelanda'], answer: 0 },
  { type: 'flag', code: 'jp', q: '¿De qué país es esta bandera?', options: ['Corea del Sur', 'China', 'Japón', 'Bangladés'], answer: 2 },
  { type: 'flag', code: 'nl', q: '¿De qué país es esta bandera?', options: ['Francia', 'Rusia', 'Luxemburgo', 'Países Bajos'], answer: 3 },
  { type: 'flag', code: 'be', q: '¿De qué país es esta bandera?', options: ['Bélgica', 'Alemania', 'Chad', 'Rumania'], answer: 0 },
  { type: 'flag', code: 'hr', q: '¿De qué país es esta bandera?', options: ['Serbia', 'Croacia', 'Eslovaquia', 'Eslovenia'], answer: 1 },
  { type: 'flag', code: 'pl', q: '¿De qué país es esta bandera?', options: ['Indonesia', 'Mónaco', 'Polonia', 'Austria'], answer: 2 },
  { type: 'flag', code: 'ma', q: '¿De qué país es esta bandera?', options: ['Marruecos', 'Turquía', 'Túnez', 'Vietnam'], answer: 0 },
  { type: 'flag', code: 'sn', q: '¿De qué país es esta bandera?', options: ['Malí', 'Senegal', 'Camerún', 'Guinea'], answer: 1 },
  { type: 'flag', code: 'kr', q: '¿De qué país es esta bandera?', options: ['Japón', 'China', 'Corea del Sur', 'Taiwán'], answer: 2 },
  { type: 'flag', code: 'us', q: '¿De qué país es esta bandera?', options: ['Reino Unido', 'USA', 'Liberia', 'Malasia'], answer: 1 },
  { type: 'flag', code: 'pe', q: '¿De qué país es esta bandera?', options: ['Perú', 'Canadá', 'Austria', 'Líbano'], answer: 0 },
  { type: 'flag', code: 'cl', q: '¿De qué país es esta bandera?', options: ['Cuba', 'Chile', 'Texas', 'Puerto Rico'], answer: 1 },
  { type: 'flag', code: 'cr', q: '¿De qué país es esta bandera?', options: ['Tailandia', 'Costa Rica', 'Corea del Norte', 'Cuba'], answer: 1 },

  // ── Banderas (dificultad media) ──
  { type: 'flag', code: 'py', q: '¿De qué país es esta bandera?', options: ['Países Bajos', 'Paraguay', 'Luxemburgo', 'Rusia'], answer: 1 },
  { type: 'flag', code: 'bo', q: '¿De qué país es esta bandera?', options: ['Bolivia', 'Ghana', 'Etiopía', 'Lituania'], answer: 0 },
  { type: 'flag', code: 've', q: '¿De qué país es esta bandera?', options: ['Colombia', 'Ecuador', 'Venezuela', 'Bolivia'], answer: 2 },
  { type: 'flag', code: 'gh', q: '¿De qué país es esta bandera?', options: ['Etiopía', 'Ghana', 'Bolivia', 'Senegal'], answer: 1 },
  { type: 'flag', code: 'et', q: '¿De qué país es esta bandera?', options: ['Ghana', 'Bolivia', 'Etiopía', 'Mali'], answer: 2 },
  { type: 'flag', code: 'cm', q: '¿De qué país es esta bandera?', options: ['Senegal', 'Mali', 'Camerún', 'Guinea'], answer: 2 },
  { type: 'flag', code: 'ci', q: '¿De qué país es esta bandera?', options: ["Costa de Marfil", 'Irlanda', 'India', 'Níger'], answer: 0 },
  { type: 'flag', code: 'ng', q: '¿De qué país es esta bandera?', options: ['Irlanda', 'Italia', 'Nigeria', 'Bangladés'], answer: 2 },
  { type: 'flag', code: 'tn', q: '¿De qué país es esta bandera?', options: ['Túnez', 'Turquía', 'Marruecos', 'Argelia'], answer: 0 },
  { type: 'flag', code: 'dz', q: '¿De qué país es esta bandera?', options: ['Pakistán', 'Argelia', 'Mauritania', 'Túnez'], answer: 1 },
  { type: 'flag', code: 'eg', q: '¿De qué país es esta bandera?', options: ['Yemen', 'Siria', 'Egipto', 'Irak'], answer: 2 },
  { type: 'flag', code: 'sa', q: '¿De qué país es esta bandera?', options: ['Arabia Saudita', 'Catar', 'Emiratos Árabes', 'Omán'], answer: 0 },
  { type: 'flag', code: 'qa', q: '¿De qué país es esta bandera?', options: ['Baréin', 'Catar', 'Emiratos Árabes', 'Kuwait'], answer: 1 },
  { type: 'flag', code: 'ir', q: '¿De qué país es esta bandera?', options: ['Irán', 'Irak', 'Afganistán', 'Tayikistán'], answer: 0 },
  { type: 'flag', code: 'au', q: '¿De qué país es esta bandera?', options: ['Nueva Zelanda', 'Australia', 'Fiyi', 'Reino Unido'], answer: 1 },
  { type: 'flag', code: 'nz', q: '¿De qué país es esta bandera?', options: ['Australia', 'Nueva Zelanda', 'Fiyi', 'Samoa'], answer: 1 },
  { type: 'flag', code: 'rs', q: '¿De qué país es esta bandera?', options: ['Serbia', 'Rusia', 'Eslovenia', 'Eslovaquia'], answer: 0 },
  { type: 'flag', code: 'ru', q: '¿De qué país es esta bandera?', options: ['Eslovaquia', 'Eslovenia', 'Rusia', 'Serbia'], answer: 2 },
  { type: 'flag', code: 'si', q: '¿De qué país es esta bandera?', options: ['Eslovaquia', 'Eslovenia', 'Serbia', 'Rusia'], answer: 1 },
  { type: 'flag', code: 'sk', q: '¿De qué país es esta bandera?', options: ['Eslovaquia', 'Eslovenia', 'Rusia', 'Serbia'], answer: 0 },
  { type: 'flag', code: 'ro', q: '¿De qué país es esta bandera?', options: ['Chad', 'Rumania', 'Moldavia', 'Andorra'], answer: 1 },
  { type: 'flag', code: 'td', q: '¿De qué país es esta bandera?', options: ['Rumania', 'Moldavia', 'Chad', 'Andorra'], answer: 2 },
  { type: 'flag', code: 'md', q: '¿De qué país es esta bandera?', options: ['Rumania', 'Moldavia', 'Andorra', 'Chad'], answer: 1 },
  { type: 'flag', code: 'ad', q: '¿De qué país es esta bandera?', options: ['Chad', 'Rumania', 'Andorra', 'Moldavia'], answer: 2 },
  { type: 'flag', code: 'hu', q: '¿De qué país es esta bandera?', options: ['Italia', 'Hungría', 'Bulgaria', 'Irlanda'], answer: 1 },
  { type: 'flag', code: 'bg', q: '¿De qué país es esta bandera?', options: ['Hungría', 'Bulgaria', 'Sierra Leona', 'Lituania'], answer: 1 },
  { type: 'flag', code: 'ie', q: '¿De qué país es esta bandera?', options: ['Irlanda', 'Italia', 'Costa de Marfil', 'México'], answer: 0 },
  { type: 'flag', code: 'in', q: '¿De qué país es esta bandera?', options: ['Níger', 'India', 'Irlanda', 'Costa de Marfil'], answer: 1 },
  { type: 'flag', code: 'ne', q: '¿De qué país es esta bandera?', options: ['India', 'Costa de Marfil', 'Níger', 'Irlanda'], answer: 2 },
  { type: 'flag', code: 'id', q: '¿De qué país es esta bandera?', options: ['Mónaco', 'Indonesia', 'Polonia', 'Singapur'], answer: 1 },
  { type: 'flag', code: 'mc', q: '¿De qué país es esta bandera?', options: ['Indonesia', 'Mónaco', 'Polonia', 'Singapur'], answer: 1 },
  { type: 'flag', code: 'sg', q: '¿De qué país es esta bandera?', options: ['Indonesia', 'Mónaco', 'Singapur', 'Polonia'], answer: 2 },
  { type: 'flag', code: 'pa', q: '¿De qué país es esta bandera?', options: ['Panamá', 'Honduras', 'El Salvador', 'Nicaragua'], answer: 0 },
  { type: 'flag', code: 'hn', q: '¿De qué país es esta bandera?', options: ['El Salvador', 'Honduras', 'Nicaragua', 'Guatemala'], answer: 1 },
  { type: 'flag', code: 'sv', q: '¿De qué país es esta bandera?', options: ['Honduras', 'El Salvador', 'Nicaragua', 'Guatemala'], answer: 1 },
  { type: 'flag', code: 'gt', q: '¿De qué país es esta bandera?', options: ['El Salvador', 'Guatemala', 'Honduras', 'Belice'], answer: 1 },
  { type: 'flag', code: 'do', q: '¿De qué país es esta bandera?', options: ['Cuba', 'Puerto Rico', 'República Dominicana', 'Haití'], answer: 2 },
  { type: 'flag', code: 'cu', q: '¿De qué país es esta bandera?', options: ['Puerto Rico', 'Cuba', 'República Dominicana', 'Texas'], answer: 1 },
  { type: 'flag', code: 'jm', q: '¿De qué país es esta bandera?', options: ['Jamaica', 'Etiopía', 'Ghana', 'Surinam'], answer: 0 },
  { type: 'flag', code: 'tr', q: '¿De qué país es esta bandera?', options: ['Túnez', 'Turquía', 'Argelia', 'Singapur'], answer: 1 },
  { type: 'flag', code: 'ca', q: '¿De qué país es esta bandera?', options: ['Perú', 'Canadá', 'Austria', 'Líbano'], answer: 1 },
  { type: 'flag', code: 'at', q: '¿De qué país es esta bandera?', options: ['Canadá', 'Perú', 'Austria', 'Líbano'], answer: 2 },
  { type: 'flag', code: 'lb', q: '¿De qué país es esta bandera?', options: ['Canadá', 'Perú', 'Líbano', 'Austria'], answer: 2 },
  { type: 'flag', code: 'gr', q: '¿De qué país es esta bandera?', options: ['Uruguay', 'Grecia', 'Israel', 'Argentina'], answer: 1 },
  { type: 'flag', code: 'il', q: '¿De qué país es esta bandera?', options: ['Uruguay', 'Grecia', 'Israel', 'Argentina'], answer: 2 },
  { type: 'flag', code: 'sz', q: '¿De qué país es esta bandera?', options: ['Suazilandia', 'Sudáfrica', 'Zimbabue', 'Botsuana'], answer: 0 },
  { type: 'flag', code: 'za', q: '¿De qué país es esta bandera?', options: ['Sudáfrica', 'Zimbabue', 'Botsuana', 'Namibia'], answer: 0 },
  { type: 'flag', code: 'lt', q: '¿De qué país es esta bandera?', options: ['Lituania', 'Letonia', 'Estonia', 'Bulgaria'], answer: 0 },
  { type: 'flag', code: 'lv', q: '¿De qué país es esta bandera?', options: ['Lituania', 'Letonia', 'Estonia', 'Mónaco'], answer: 1 },
  { type: 'flag', code: 'ee', q: '¿De qué país es esta bandera?', options: ['Letonia', 'Estonia', 'Lituania', 'Finlandia'], answer: 1 },

  // ── Banderas (lote 2) ──
  { type: 'flag', code: 'ch', q: '¿De qué país es esta bandera?', options: ['Dinamarca', 'Suiza', 'Inglaterra', 'Georgia'], answer: 1 },
  { type: 'flag', code: 'dk', q: '¿De qué país es esta bandera?', options: ['Suiza', 'Noruega', 'Dinamarca', 'Islandia'], answer: 2 },
  { type: 'flag', code: 'no', q: '¿De qué país es esta bandera?', options: ['Islandia', 'Noruega', 'Dinamarca', 'Finlandia'], answer: 1 },
  { type: 'flag', code: 'se', q: '¿De qué país es esta bandera?', options: ['Suecia', 'Finlandia', 'Noruega', 'Ucrania'], answer: 0 },
  { type: 'flag', code: 'fi', q: '¿De qué país es esta bandera?', options: ['Suecia', 'Finlandia', 'Islandia', 'Grecia'], answer: 1 },
  { type: 'flag', code: 'is', q: '¿De qué país es esta bandera?', options: ['Noruega', 'Islandia', 'Dinamarca', 'Eslovaquia'], answer: 1 },
  { type: 'flag', code: 'ua', q: '¿De qué país es esta bandera?', options: ['Suecia', 'Ucrania', 'Kazajistán', 'Rumania'], answer: 1 },
  { type: 'flag', code: 'ge', q: '¿De qué país es esta bandera?', options: ['Inglaterra', 'Georgia', 'Suiza', 'Dinamarca'], answer: 1 },
  { type: 'flag', code: 'cn', q: '¿De qué país es esta bandera?', options: ['Vietnam', 'China', 'Turquía', 'Túnez'], answer: 1 },
  { type: 'flag', code: 'vn', q: '¿De qué país es esta bandera?', options: ['China', 'Vietnam', 'Marruecos', 'Turquía'], answer: 1 },
  { type: 'flag', code: 'th', q: '¿De qué país es esta bandera?', options: ['Costa Rica', 'Tailandia', 'Países Bajos', 'Croacia'], answer: 1 },
  { type: 'flag', code: 'ph', q: '¿De qué país es esta bandera?', options: ['Filipinas', 'Cuba', 'Puerto Rico', 'Chile'], answer: 0 },
  { type: 'flag', code: 'pk', q: '¿De qué país es esta bandera?', options: ['Argelia', 'Pakistán', 'Turquía', 'Mauritania'], answer: 1 },
  { type: 'flag', code: 'ke', q: '¿De qué país es esta bandera?', options: ['Sudáfrica', 'Kenia', 'Malaui', 'Zimbabue'], answer: 1 },

  // ── Jugadores legendarios (type 'player': muestra una foto) ──
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg/250px-Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg', q: '¿Quién es este jugador?', options: ['Lionel Messi', 'Ángel Di María', 'Sergio Agüero', 'Neymar'], answer: 0 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Cristiano_Ronaldo_Al-Nassr_2023.jpg/250px-Cristiano_Ronaldo_Al-Nassr_2023.jpg', q: '¿Quién es este jugador?', options: ['Ronaldo Nazário', 'Cristiano Ronaldo', 'Kaká', 'Luís Figo'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Ronaldo_Naz%C3%A1rio.jpg/250px-Ronaldo_Naz%C3%A1rio.jpg', q: '¿Quién es este jugador (apodado "El Fenómeno")?', options: ['Cristiano Ronaldo', 'Romário', 'Ronaldo Nazário', 'Ronaldinho'], answer: 2 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Maradona_1986_vs_italy.jpg/250px-Maradona_1986_vs_italy.jpg', q: '¿Quién es este jugador?', options: ['Diego Maradona', 'Mario Kempes', 'Gabriel Batistuta', 'Lionel Messi'], answer: 0 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pele_celebrating_1970_%28cropped%29.jpg/250px-Pele_celebrating_1970_%28cropped%29.jpg', q: '¿Quién es este jugador?', options: ['Garrincha', 'Pelé', 'Zico', 'Romário'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Zinedine_Zidane_2018.jpg/250px-Zinedine_Zidane_2018.jpg', q: '¿Quién es este jugador (campeón del mundo con Francia en 1998)?', options: ['Thierry Henry', 'Zinedine Zidane', 'Didier Deschamps', 'Franck Ribéry'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Neymar_850_1705.jpg/250px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Neymar_850_1705.jpg', q: '¿Quién es este jugador?', options: ['Vinícius Júnior', 'Neymar', 'Gabriel Jesus', 'Richarlison'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Kylian_Mbappe_2017.jpg/250px-Kylian_Mbappe_2017.jpg', q: '¿Quién es este jugador?', options: ['Antoine Griezmann', 'Ousmane Dembélé', 'Kylian Mbappé', 'Karim Benzema'], answer: 2 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ronaldinho_in_2019.jpg/250px-Ronaldinho_in_2019.jpg', q: '¿Quién es este jugador (Balón de Oro 2005)?', options: ['Ronaldinho', 'Ronaldo Nazário', 'Kaká', 'Roberto Carlos'], answer: 0 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Andr%C3%A9s_Iniesta_2018.jpg/250px-Andr%C3%A9s_Iniesta_2018.jpg', q: '¿Quién es este jugador (gol del título mundial 2010)?', options: ['Xavi Hernández', 'Andrés Iniesta', 'David Villa', 'Sergio Busquets'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Xavi_Hern%C3%A1ndez_-_002_%28cropped%29.jpg/250px-Xavi_Hern%C3%A1ndez_-_002_%28cropped%29.jpg', q: '¿Quién es este jugador?', options: ['Andrés Iniesta', 'Xavi Hernández', 'Sergio Ramos', 'David Silva'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Iker_Casillas_2018.jpg/250px-Iker_Casillas_2018.jpg', q: '¿Quién es este arquero campeón del mundo 2010?', options: ['Gianluigi Buffon', 'Iker Casillas', 'Manuel Neuer', 'David De Gea'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sergio_Ramos_10mar2007.jpg/250px-Sergio_Ramos_10mar2007.jpg', q: '¿Quién es este defensa español?', options: ['Gerard Piqué', 'Sergio Ramos', 'Carles Puyol', 'Jordi Alba'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Luka_Modric_2015.jpg/250px-Luka_Modric_2015.jpg', q: '¿Quién es este jugador (Balón de Oro 2018)?', options: ['Ivan Rakitić', 'Luka Modrić', 'Toni Kroos', 'Marcelo'], answer: 1 },
  { type: 'player', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Robert_Lewandowski_2018.jpg/250px-Robert_Lewandowski_2018.jpg', q: '¿Quién es este delantero polaco?', options: ['Robert Lewandowski', 'Wojciech Szczęsny', 'Arkadiusz Milik', 'Piotr Zieliński'], answer: 0 },

  // ── Valores de Andersen (cat: 'andersen' → siempre sale 1 por reto) ──
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuántos valores tiene la firma?', options: ['3', '4', '5', '6'], answer: 2 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuál de estos NO es un valor de la firma?', options: ['Excelencia', 'Innovación', 'Independencia', 'Transparencia'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Valor de Andersen: "ser un referente de calidad en el sector". ¿Cuál es?', options: ['Compromiso', 'Excelencia', 'Continuidad', 'Transparencia'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Valor de Andersen: "contratar a los mejores e invertir en el equipo para asegurar un legado". ¿Cuál es?', options: ['Compromiso', 'Independencia', 'Excelencia', 'Transparencia'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Valor de Andersen: "representar a los clientes de manera objetiva e independiente". ¿Cuál es?', options: ['Independencia', 'Continuidad', 'Compromiso', 'Excelencia'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Valor de Andersen: "un proyecto global con el máximo nivel de servicio en cualquier lugar". ¿Cuál es?', options: ['Transparencia', 'Continuidad', 'Compromiso', 'Independencia'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Valor de Andersen: "comunicación abierta, intercambio de información y decisiones conjuntas". ¿Cuál es?', options: ['Transparencia', 'Excelencia', 'Independencia', 'Continuidad'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Qué valor se relaciona con dar consejos objetivos, sin conflictos de interés?', options: ['Continuidad', 'Independencia', 'Excelencia', 'Compromiso'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Qué valor habla de un proyecto global y servicio en cualquier parte del mundo?', options: ['Continuidad', 'Transparencia', 'Compromiso', 'Excelencia'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Andersen — "Valoramos la comunicación abierta y la toma de decisiones conjuntas" describe el valor de…', options: ['Compromiso', 'Transparencia', 'Independencia', 'Continuidad'], answer: 1 },

  // ── Frentes / líneas de servicio de Andersen Ecuador ──
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuántas líneas de negocio CONSOLIDADAS tiene la firma?', options: ['2', '3', '4', '5'], answer: 2 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuántas líneas de negocio están "por consolidar" (en crecimiento)?', options: ['2', '3', '4', '5'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuál de estas NO es una línea de negocio consolidada?', options: ['Consultoría', 'Economía', 'Impuestos', 'Cumplimiento'], answer: 3 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cuál de estas NO es una línea de negocio por consolidar?', options: ['Patrimonio Privado', 'Transformación de negocios', 'Cumplimiento', 'Patrocinio'], answer: 3 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se traduce "Consultoría" en inglés según el organigrama de frentes?', options: ['Tax Advisory & BPO', 'Corporate & Private Advisory', 'Business Growth & Transformation', 'Compliance'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se traduce "Economía" en inglés según el organigrama de frentes?', options: ['Economic & Business', 'Private Wealth', 'Tax Controversy', 'Compliance'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se traduce "Impuestos" en inglés según el organigrama de frentes?', options: ['Tax Advisory & BPO', 'Tax Controversy', 'Compliance', 'Corporate & Private Advisory'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se traduce "Patrocinio" en inglés según el organigrama de frentes?', options: ['Private Wealth', 'Tax Controversy', 'Compliance', 'Business Growth & Transformation'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se llama en inglés la línea "Patrimonio Privado"?', options: ['Private Wealth', 'Corporate Advisory', 'Tax Controversy', 'Business Transformation'], answer: 0 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Cómo se llama en inglés la línea "Transformación de negocios"?', options: ['Compliance', 'Private Wealth', 'Business Growth & Transformation', 'Tax Advisory'], answer: 2 },
  { type: 'text', cat: 'andersen', q: 'Andersen — Según el mensaje de los frentes: "Las grandes selecciones no ganan por tener estrellas, ganan por…"', options: ['tener más jugadores', 'una alineación diseñada para ejecutar una estrategia', 'tener al mejor entrenador', 'gastar más dinero'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Qué frase describe a Consultoría, Economía, Impuestos y Patrocinio?', options: ['Líneas a consolidar', 'Líneas de negocio consolidadas', 'Líneas internacionales', 'Líneas administrativas'], answer: 1 },
  { type: 'text', cat: 'andersen', q: 'Andersen — ¿Qué frase describe a Patrimonio Privado, Transformación de negocios y Cumplimiento?', options: ['Líneas consolidadas', 'Líneas de negocio a consolidar (con las que queremos crecer)', 'Líneas que se van a cerrar', 'Líneas solo internacionales'], answer: 1 },
];
