function cap(s) { return s[0].toUpperCase() + s.slice(1); }

// sex: 'M' (hombre) | 'F' (mujer) — inferido por nombre de pila.
// Nombres ambiguos para los que se asumió un valor (avisar si alguno está mal):
// dexer.chinga (M), tais.guachambo (F), hower.leon (M), farina.morejon (F),
// lesny.pico (F), alex.ponce (M), alexis.robayo (M).
const EMPLOYEE_DATA = [
  { username: 'raissa.aguila', password: '0923499669', department: 'Administracion', sex: 'F' },
  { username: 'sandy.alava', password: '0941657116', department: 'Capital Humano', sex: 'F' },
  { username: 'yajaira.alvarado', password: '0922012588', department: 'Nuevos Negocios', sex: 'F' },
  { username: 'britney.alvarez', password: '0954199733', department: 'Impuestos', sex: 'F' },
  { username: 'astrid.alvarez', password: '0952756823', department: 'Comercial', sex: 'F' },
  { username: 'zoila.andrade', password: '0950617696', department: 'Impuestos', sex: 'F' },
  { username: 'abraham.anzules', password: '0952174795', department: 'Impuestos', sex: 'M' },
  { username: 'ana.aponte', password: '0929953156', department: 'Impuestos', sex: 'F' },
  { username: 'ambar.aragundy', password: '0950413237', department: 'Impuestos', sex: 'F' },
  { username: 'josue.arriaga', password: '0955407986', department: 'Administracion', sex: 'M' },
  { username: 'kristel.arriaga', password: '0957522824', department: 'Impuestos', sex: 'F' },
  { username: 'diana.bajana', password: '0922645247', department: 'Impuestos', sex: 'F' },
  { username: 'leandro.barona', password: '0950184515', department: 'Impuestos', sex: 'M' },
  { username: 'aurelio.barreto', password: '0952812527', department: 'Impuestos', sex: 'M' },
  { username: 'beatriz.bolanos', password: '0930433867', department: 'Consultoria', sex: 'F' },
  { username: 'raul.bolanos', password: '0953300472', department: 'Impuestos', sex: 'M' },
  { username: 'marlon.bonilla', password: '0929024024', department: 'Impuestos', sex: 'M' },
  { username: 'francisco.briones', password: '0925017691', department: 'Economía Y Empresa', sex: 'M' },
  { username: 'alfredo.bustos', password: '0914339460', department: 'Impuestos', sex: 'M' },
  { username: 'daniel.bustos', password: '1725377152', department: 'Consultoria', sex: 'M' },
  { username: 'hector.calderon', password: '0954713392', department: 'Impuestos', sex: 'M' },
  { username: 'mercedes.calderon', password: '0958652000', department: 'Impuestos', sex: 'F' },
  { username: 'sofia.carranza', password: '0914248182', department: 'Contabilidad/Finanzas', sex: 'F' },
  { username: 'christian.castro', password: '0959142027', department: 'Impuestos', sex: 'M' },
  { username: 'kevin.castro', password: '0954428868', department: 'Nuevos Negocios', sex: 'M' },
  { username: 'carlos.cedillo', password: '0956203855', department: 'Administracion', sex: 'M' },
  { username: 'valentina.chavez', password: '0941293284', department: 'Administracion', sex: 'F' },
  { username: 'diego.chavez', password: '0931215115', department: 'Consultoria', sex: 'M' },
  { username: 'lissette.chele', password: '0954095956', department: 'Impuestos', sex: 'F' },
  { username: 'dexer.chinga', password: '0951946524', department: 'Impuestos', sex: 'M' },
  { username: 'gabriel.chiriboga', password: '0953290863', department: 'Impuestos', sex: 'M' },
  { username: 'cristhian.contreras', password: '1207701671', department: 'Impuestos', sex: 'M' },
  { username: 'jefferson.cordova', password: '1206597484', department: 'Impuestos', sex: 'M' },
  { username: 'marlon.cruz', password: '0944071380', department: 'Contabilidad/Finanzas', sex: 'M' },
  { username: 'katherine.deloor', password: '1206713610', department: 'Impuestos', sex: 'F' },
  { username: 'fiorella.demori', password: '0953327327', department: 'Impuestos', sex: 'F' },
  { username: 'josue.demera', password: '0954865804', department: 'Impuestos', sex: 'M' },
  { username: 'ashley.endara', password: '0958215774', department: 'Impuestos', sex: 'F' },
  { username: 'luis.escudero', password: '0931216782', department: 'Capital Humano', sex: 'M' },
  { username: 'julio.fernandez', password: '0922533476', department: 'Patrocinio', sex: 'M' },
  { username: 'natalie.firmat', password: '0930574629', department: 'Marketing', sex: 'F' },
  { username: 'miguel.franco', password: '0944230135', department: 'Impuestos', sex: 'M' },
  { username: 'kenia.franco', password: '0952688786', department: 'Marketing', sex: 'F' },
  { username: 'freddy.garcia', password: '1206485359', department: 'Economía Y Empresa', sex: 'M' },
  { username: 'keila.gonzabay', password: '0956763726', department: 'Impuestos', sex: 'F' },
  { username: 'paola.gonzalez', password: '0941564767', department: 'Impuestos', sex: 'F' },
  { username: 'tais.guachambo', password: '0955433735', department: 'Impuestos', sex: 'F' },
  { username: 'douglas.gualpa', password: '0954544995', department: 'Impuestos', sex: 'M' },
  { username: 'nayely.guaman', password: '0929567352', department: 'Impuestos', sex: 'F' },
  { username: 'jennifer.guasco', password: '0951037670', department: 'Impuestos', sex: 'F' },
  { username: 'dulce.guevara', password: '0944180579', department: 'Impuestos', sex: 'F' },
  { username: 'pablo.guevara', password: '0909907297', department: 'Consultoria', sex: 'M' },
  { username: 'anahi.gutierrez', password: '0943988337', department: 'Impuestos', sex: 'F' },
  { username: 'vianna.hermosa', password: '0916918188', department: 'Consultoria', sex: 'F' },
  { username: 'irene.holguin', password: '0951270396', department: 'Contabilidad/Finanzas', sex: 'F' },
  { username: 'madeleine.holguin', password: '0955293519', department: 'Impuestos', sex: 'F' },
  { username: 'jhon.indio', password: '0927756627', department: 'Administracion', sex: 'M' },
  { username: 'luis.iniga', password: '0927025643', department: 'Impuestos', sex: 'M' },
  { username: 'gia.jimbo', password: '0926417775', department: 'Contabilidad/Finanzas', sex: 'F' },
  { username: 'stephany.lara', password: '0954682795', department: 'Impuestos', sex: 'F' },
  { username: 'juliana.lazaro', password: '0942984790', department: 'Impuestos', sex: 'F' },
  { username: 'hower.leon', password: '0955775622', department: 'Impuestos', sex: 'M' },
  { username: 'daniel.leon', password: '1309101283', department: 'Nuevos Negocios', sex: 'M' },
  { username: 'jose.leon', password: '0956620504', department: 'Impuestos', sex: 'M' },
  { username: 'fiorella.limones', password: '0954893137', department: 'Consultoria', sex: 'F' },
  { username: 'sara.lopez', password: '1722470034', department: 'Consultoria', sex: 'F' },
  { username: 'grace.lopez', password: '0923194104', department: 'Nuevos Negocios', sex: 'F' },
  { username: 'gabriela.romero', password: '0954575528', department: 'Nuevos Negocios', sex: 'F' },
  { username: 'jeancarlos.marcillo', password: '0926801606', department: 'Consultoria', sex: 'M' },
  { username: 'joao.marcillo', password: '0951981778', department: 'Impuestos', sex: 'M' },
  { username: 'romina.mariduena', password: '0950359562', department: 'Patrocinio', sex: 'F' },
  { username: 'karla.matamoros', password: '0952464048', department: 'Capital Humano', sex: 'F' },
  { username: 'amy.mendoza', password: '0952829935', department: 'Impuestos', sex: 'F' },
  { username: 'alejandro.merchan', password: '0956709836', department: 'Contabilidad/Finanzas', sex: 'M' },
  { username: 'madelyne.meza', password: '0950518720', department: 'Impuestos', sex: 'F' },
  { username: 'jonathan.minga', password: '0950513812', department: 'Impuestos', sex: 'M' },
  { username: 'azael.mite', password: '0927701573', department: 'Impuestos', sex: 'M' },
  { username: 'camila.mora', password: '0750104168', department: 'Patrocinio', sex: 'F' },
  { username: 'oscar.morales', password: '1312333766', department: 'Administracion', sex: 'M' },
  { username: 'melany.moreira', password: '0955335948', department: 'Impuestos', sex: 'F' },
  { username: 'farina.morejon', password: '0924163199', department: 'Impuestos', sex: 'F' },
  { username: 'abel.murillo', password: '0956718241', department: 'Impuestos', sex: 'M' },
  { username: 'marcelo.murillo', password: '0952557635', department: 'Impuestos', sex: 'M' },
  { username: 'jenniffer.narvaez', password: '0952700839', department: 'Impuestos', sex: 'F' },
  { username: 'dennis.noboa', password: '0926068875', department: 'Comercial', sex: 'M' },
  { username: 'marcelo.orellana', password: '0954326369', department: 'Patrocinio', sex: 'M' },
  { username: 'mario.orelllana', password: '0917012007', department: 'Patrocinio', sex: 'M' },
  { username: 'kleber.padilla', password: '0955179544', department: 'Capital Humano', sex: 'M' },
  { username: 'amina.palacios', password: '1729857589', department: 'Impuestos', sex: 'F' },
  { username: 'andres.pardo', password: '0954427233', department: 'Contabilidad/Finanzas', sex: 'M' },
  { username: 'daniela.paredes', password: '0951191410', department: 'Impuestos', sex: 'F' },
  { username: 'mariana.pastor', password: '0926276833', department: 'Marketing', sex: 'F' },
  { username: 'vicente.pazmino', password: '0915823579', department: 'Impuestos', sex: 'M' },
  { username: 'yamilet.penaherrera', password: '0952991719', department: 'Impuestos', sex: 'F' },
  { username: 'lesny.pico', password: '0950645176', department: 'Impuestos', sex: 'F' },
  { username: 'angely.pincay', password: '1314265784', department: 'Impuestos', sex: 'F' },
  { username: 'francisco.pita', password: '0950821736', department: 'Impuestos', sex: 'M' },
  { username: 'lilibeth.plaza', password: '0927184853', department: 'Impuestos', sex: 'F' },
  { username: 'judith.pluas', password: '0953987518', department: 'Impuestos', sex: 'F' },
  { username: 'alex.ponce', password: '0950591487', department: 'Impuestos', sex: 'M' },
  { username: 'kevin.preciado', password: '0931160634', department: 'Impuestos', sex: 'M' },
  { username: 'isorela.puglla', password: '0923664882', department: 'Impuestos', sex: 'F' },
  { username: 'ninoska.quijano', password: '0953540796', department: 'Impuestos', sex: 'F' },
  { username: 'naomy.quimis', password: '1313555516', department: 'Impuestos', sex: 'F' },
  { username: 'marcos.quinde', password: '0953523206', department: 'Impuestos', sex: 'M' },
  { username: 'iveth.quinto', password: '0944384858', department: 'Impuestos', sex: 'F' },
  { username: 'johnny.quinonez', password: '1207689280', department: 'Impuestos', sex: 'M' },
  { username: 'diana.quishpillo', password: '0953627098', department: 'Impuestos', sex: 'F' },
  { username: 'alexis.robayo', password: '0930872734', department: 'Patrocinio', sex: 'M' },
  { username: 'abraham.rodriguez', password: '0958307464', department: 'Impuestos', sex: 'M' },
  { username: 'sebastian.rodriguez', password: '0941651085', department: 'Consultoria', sex: 'M' },
  { username: 'luciana.salame', password: '0920527025', department: 'Consultoria', sex: 'F' },
  { username: 'lissette.sanchez', password: '0927171231', department: 'Impuestos', sex: 'F' },
  { username: 'gabriel.solis', password: '0927201483', department: 'Administracion', sex: 'M' },
  { username: 'karen.suarez', password: '0954190179', department: 'Administracion', sex: 'F' },
  { username: 'samuel.suarez', password: '0932414857', department: 'Comercial', sex: 'M' },
  { username: 'ricardo.taipe', password: '0926369075', department: 'Administracion', sex: 'M' },
  { username: 'jose.teran', password: '1718727272', department: 'Consultoria', sex: 'M' },
  { username: 'lady.toala', password: '0943322792', department: 'Impuestos', sex: 'F' },
  { username: 'carlos.torres', password: '0950310573', department: 'Impuestos', sex: 'M' },
  { username: 'ruben.tubay', password: '0932171341', department: 'Impuestos', sex: 'M' },
  { username: 'allan.vargas', password: '0950218917', department: 'Impuestos', sex: 'M' },
  { username: 'jose.vega', password: '0930489356', department: 'Impuestos', sex: 'M' },
  { username: 'maria.velastegui', password: '0943896761', department: 'Impuestos', sex: 'F' },
  { username: 'gabriela.verdesoto', password: '0955465752', department: 'Consultoria', sex: 'F' },
  { username: 'joffre.villegas', password: '0957258502', department: 'Impuestos', sex: 'M' },
  { username: 'roger.yagual', password: '0928505460', department: 'Impuestos', sex: 'M' },
  { username: 'briggitte.yupa', password: '0957664196', department: 'Impuestos', sex: 'F' },
  { username: 'francisco.zabala', password: '0925312563', department: 'Impuestos', sex: 'M' },
  { username: 'solange.zambrano', password: '0928814722', department: 'Contabilidad/Finanzas', sex: 'F' },
  { username: 'daniela.zorrilla', password: '0953292240', department: 'Impuestos', sex: 'F' },
  { username: 'german.zuniga', password: '0930861281', department: 'Administracion', sex: 'M' },
];

export const USERS = EMPLOYEE_DATA.map((e, i) => {
  const parts = e.username.split('.');
  return {
    id: i + 1,
    username: e.username,
    password: e.password,
    displayName: parts.map(cap).join(' '),
    email: `${e.username}@ec.andersen.com`,
    avatarInitials: parts.map(p => p[0].toUpperCase()).join('').slice(0, 2),
    department: e.department,
    sex: e.sex,
  };
});

// Ex-empleados: ya no aparecen en ningún lado (álbum, posiciones, fichas).
// Sus datos siguen en la base, pero se ocultan en el front.
export const EXCLUDED_USERS = ['gabriela.guerrero', 'angelica.lainez'];
export const isExcluded = (username) => EXCLUDED_USERS.includes((username || '').toLowerCase());

export function findUser(username, password) {
  const u = username.trim().toLowerCase();
  const user = USERS.find(x => x.username === u);
  if (!user) return null;
  try {
    const overrides = JSON.parse(localStorage.getItem('wc2026_pw_overrides') || '{}');
    const effective = overrides[u] || user.password;
    return effective === password ? user : null;
  } catch {
    return user.password === password ? user : null;
  }
}