const PASSWORD = 'Mundial2026';

function cap(s) { return s[0].toUpperCase() + s.slice(1); }

const MAILS = [
  'raissa.aguila@ec.Andersen.com',
  'sandy.alava@ec.Andersen.com',
  'saray.aleman@ec.Andersen.com',
  'ingrid.almeida@ec.Andersen.com',
  'cristina.altamirano@ec.Andersen.com',
  'yajaira.alvarado@ec.Andersen.com',
  'britney.alvarez@ec.Andersen.com',
  'juan.alvarez@ec.Andersen.com',
  'luis.andrade@ec.Andersen.com',
  'zoila.andrade@ec.Andersen.com',
  'abraham.anzules@ec.Andersen.com',
  'ana.aponte@ec.Andersen.com',
  'ambar.aragundy@ec.Andersen.com',
  'adriana.arcos@ec.Andersen.com',
  'vanessa.arguello@ec.Andersen.com',
  'nohelia.arreaga@ec.Andersen.com',
  'kristel.arriaga@ec.Andersen.com',
  'diana.bajana@ec.Andersen.com',
  'domenica.baldeon@ec.Andersen.com',
  'Daniela.Banegas@ec.Andersen.com',
  'dante.bardellini@ec.Andersen.com',
  'leandro.barona@ec.Andersen.com',
  'aurelio.barreto@ec.Andersen.com',
  'emilio.bazurto@ec.Andersen.com',
  'beatriz.bolanos@ec.Andersen.com',
  'raul.bolanos@ec.Andersen.com',
  'marlon.bonilla@ec.Andersen.com',
  'joselin.borja@ec.Andersen.com',
  'francisco.briones@ec.Andersen.com',
  'gabriela.burgos@ec.Andersen.com',
  'alfredo.bustos@ec.Andersen.com',
  'daniel.bustos@ec.Andersen.com',
  'mercedes.calderon@ec.Andersen.com',
  'hector.calderon@ec.Andersen.com',
  'milena.canote@ec.Andersen.com',
  'sofia.carranza@ec.Andersen.com',
  'christian.castro@ec.Andersen.com',
  'kevin.castro@ec.Andersen.com',
  'adrian.cercado@ec.Andersen.com',
  'noemi.cevallos@ec.Andersen.com',
  'johnny.chacon@ec.Andersen.com',
  'diego.chavez@ec.Andersen.com',
  'Indira.Siongtay@ec.Andersen.com',
  'lissette.chele@ec.Andersen.com',
  'aleida.cherres@ec.Andersen.com',
  'dexer.chinga@ec.Andersen.com',
  'gabriel.chiriboga@ec.Andersen.com',
  'wilson.cobo@ec.Andersen.com',
  'cristhian.contreras@ec.Andersen.com',
  'jefferson.cordova@ec.Andersen.com',
  'kenya.crespin@ec.Andersen.com',
  'marlon.cruz@ec.Andersen.com',
  'katherine.deloor@ec.Andersen.com',
  'fiorella.demori@ec.Andersen.com',
  'josue.demera@ec.Andersen.com',
  'ashley.endara@ec.Andersen.com',
  'ivan.enriquez@ec.Andersen.com',
  'luis.escudero@ec.Andersen.com',
  'gloria.fernandez@ec.Andersen.com',
  'julio.fernandez@ec.Andersen.com',
  'miguel.franco@ec.Andersen.com',
  'andy.garces@ec.Andersen.com',
  'freddy.garcia@ec.Andersen.com',
  'emilio.garzon@ec.Andersen.com',
  'keila.gonzabay@ec.Andersen.com',
  'paola.gonzalez@ec.Andersen.com',
  'pierina.granados@ec.Andersen.com',
  'tais.guachambo@ec.Andersen.com',
  'douglas.gualpa@ec.Andersen.com',
  'nayely.guaman@ec.Andersen.com',
  'jennifer.guasco@ec.Andersen.com',
  'gabriela.guerrero@ec.Andersen.com',
  'dulce.guevara@ec.Andersen.com',
  'pablo.guevara@ec.Andersen.com',
  'anahi.gutierrez@ec.Andersen.com',
  'jorge.heupel@ec.Andersen.com',
  'irene.holguin@ec.Andersen.com',
  'madeleine.holguin@ec.Andersen.com',
  'luis.iniga@ec.Andersen.com',
  'angelica.lainez@ec.Andersen.com',
  'stephany.lara@ec.Andersen.com',
  'gianpaolo.lauri@ec.Andersen.com',
  'Juliana.Lazaro@ec.Andersen.com',
  'hower.leon@ec.Andersen.com',
  'daniel.leon@ec.Andersen.com',
  'wellington.leon@ec.Andersen.com',
  'jose.leon@ec.Andersen.com',
  'fiorella.limones@ec.Andersen.com',
  'arianna.lindao@ec.Andersen.com',
  'julio.loayza@ec.Andersen.com',
  'sara.lopez@ec.Andersen.com',
  'grace.lopez@ec.Andersen.com',
  'belen.luces@ec.Andersen.com',
  'Michelle.Moran@ec.Andersen.com',
  'jeancarlos.marcillo@ec.Andersen.com',
  'joao.marcillo@ec.Andersen.com',
  'romina.mariduena@ec.Andersen.com',
  'francisco.mena@ec.Andersen.com',
  'amy.mendoza@ec.Andersen.com',
  'alejandro.merchan@ec.Andersen.com',
  'madelyne.meza@ec.Andersen.com',
  'Jonathan.Minga@ec.Andersen.com',
  'azael.mite@ec.Andersen.com',
  'allisson.monar@ec.Andersen.com',
  'carlos.montiel@ec.Andersen.com',
  'camila.mora@ec.Andersen.com',
  'sindy.moran@ec.Andersen.com',
  'melany.moreira@ec.Andersen.com',
  'jemima.moreira@ec.Andersen.com',
  'farina.morejon@ec.Andersen.com',
  'gustavo.moreno@ec.Andersen.com',
  'jhon.munoz@ec.Andersen.com',
  'abel.murillo@ec.Andersen.com',
  'marcelo.murillo@ec.Andersen.com',
  'jenniffer.narvaez@ec.Andersen.com',
  'dennis.noboa@ec.Andersen.com',
  'mario.orellana@ec.Andersen.com',
  'marcelo.orellana@ec.Andersen.com',
  'miguel.orozco@ec.Andersen.com',
  'Adriana.Paguay@ec.Andersen.com',
  'amina.palacios@ec.Andersen.com',
  'Andres.Pardo@ec.Andersen.com',
  'gabriel.paredes@ec.Andersen.com',
  'daniela.paredes@ec.Andersen.com',
  'mariana.pastor@ec.Andersen.com',
  'vicente.pazmino@ec.Andersen.com',
  'daniel.penafiel@ec.Andersen.com',
  'isabel.penaherrera@ec.Andersen.com',
  'yamilet.penaherrera@ec.Andersen.com',
  'aracely.pesantez@ec.Andersen.com',
  'lesny.pico@ec.Andersen.com',
  'melanny.pincay@ec.Andersen.com',
  'angely.pincay@ec.Andersen.com',
  'sofia.pinduisaca@ec.Andersen.com',
  'francisco.pita@ec.Andersen.com',
  'lilibeth.plaza@ec.Andersen.com',
  'judith.pluas@ec.Andersen.com',
  'alex.ponce@ec.Andersen.com',
  'kevin.preciado@ec.Andersen.com',
  'isorela.puglla@ec.Andersen.com',
  'ninoska.quijano@ec.Andersen.com',
  'Naomy.Quimis@ec.Andersen.com',
  'michelle.quinde@ec.Andersen.com',
  'marcos.quinde@ec.Andersen.com',
  'johnny.quinonez@ec.Andersen.com',
  'iveth.quinto@ec.Andersen.com',
  'john.quiroz@ec.Andersen.com',
  'josua.quirumbay@ec.Andersen.com',
  'diana.quishpillo@ec.Andersen.com',
  'isabella.raymond@ec.Andersen.com',
  'mauricio.reyes@ec.Andersen.com',
  'alfonso.rios@ec.Andersen.com',
  'genesis.rizzo@ec.Andersen.com',
  'alexis.robayo@ec.Andersen.com',
  'abraham.rodriguez@ec.Andersen.com',
  'sebastian.rodriguez@ec.Andersen.com',
  'gabriela.romero@ec.Andersen.com',
  'willian.rosado@ec.Andersen.com',
  'naomy.rosas@ec.Andersen.com',
  'luciana.salame@ec.Andersen.com',
  'lissette.sanchez@ec.Andersen.com',
  'denisse.sares@ec.Andersen.com',
  'luis.sarmiento@ec.Andersen.com',
  'miguel.silva@ec.Andersen.com',
  'milena.soledispa@ec.Andersen.com',
  'rosalinda.soriano@ec.Andersen.com',
  'karen.suarez@ec.Andersen.com',
  'samuel.suarez@ec.Andersen.com',
  'ricardo.taipe@ec.Andersen.com',
  'selene.tapia@ec.Andersen.com',
  'paulina.tirsio@ec.Andersen.com',
  'lady.toala@ec.Andersen.com',
  'veronica.tomala@ec.Andersen.com',
  'melanny.tomala@ec.Andersen.com',
  'kevin.torres@ec.Andersen.com',
  'carlos.torres@ec.Andersen.com',
  'ruben.tubay@ec.Andersen.com',
  'allan.vargas@ec.Andersen.com',
  'jose.vega@ec.Andersen.com',
  'samira.velastegui@ec.Andersen.com',
  'maria.velastegui@ec.Andersen.com',
  'gabriela.verdesoto@ec.Andersen.com',
  'samantha.villacis@ec.Andersen.com',
  'joffre.villegas@ec.Andersen.com',
  'joyce.villon@ec.Andersen.com',
  'erick.vitores@ec.Andersen.com',
  'cindy.vivar@ec.Andersen.com',
  'roger.yagual@ec.Andersen.com',
  'briggitte.yupa@ec.Andersen.com',
  'francisco.zabala@ec.Andersen.com',
  'solange.zambrano@ec.Andersen.com',
  'tonny.zambrano@ec.Andersen.com',
  'belen.zambrano@ec.Andersen.com',
  'daniela.zorrilla@ec.Andersen.com',
];

export const USERS = MAILS.map((mail, i) => {
  const username = mail.split('@')[0].toLowerCase();
  const parts = username.split('.');
  return {
    id: i + 1,
    username,
    password: PASSWORD,
    displayName: parts.map(cap).join(' '),
    email: mail.toLowerCase(),
    avatarInitials: parts.map(p => p[0].toUpperCase()).join('').slice(0, 2),
    department: 'Andersen Ecuador',
  };
});

export function findUser(username, password) {
  const u = username.trim().toLowerCase();
  const user = USERS.find(x => x.username === u);
  if (!user) return null;
  try {
    const overrides = JSON.parse(localStorage.getItem('wc2026_pw_overrides') || '{}');
    const effective = overrides[u] || user.password;
    return effective === password ? user : null;
  } catch {
    return user.password === password ? user : null;
  }
}
